---
version: '3.6'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data
    ports:
      - 5551:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: spark1
      POSTGRES_PASSWORD: password
